name = "urban-canvas-frontend"
main = "dist/index.html"
compatibility_date = "2024-01-01"

[site]
bucket = "dist"

[[kv_namespaces]]
binding = "URBAN_CANVAS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[env.production]
name = "urban-canvas-frontend"
route = "yourdomainname.com/*"

[env.staging]
name = "urban-canvas-frontend-staging"